### ISSUE TITLE
如果需要二值化, 字符切割等函数进行微调

### ISSUE THREAD

**Issue by MasterJoyHunan** [SuInk/go-captcha-recognition#1]
1. 具体怎么调整?
2. 需要调整那些参数?
3. 各参数代表的什么意思?
```
	if r < 0x7788 && imgConnect(ru, rd, rl, rr) {
		binImg.Set(x, y, color.White)
	} else {
		binImg.Set(x, y, color.Black)
	}
```
这里调整的是` 0x7788 `这个值吗?

**Comment by SuInk** [comment]
https://blog.csdn.net/qq_35392791/article/details/123813363
https://blog.csdn.net/qq_45738177/article/details/124518712
参照这两个教程，0x7788就是一个灰度值。

**Comment by MasterJoyHunan** [comment]
> https://blog.csdn.net/qq_35392791/article/details/123813363 https://blog.csdn.net/qq_45738177/article/details/124518712 参照这两个教程，0x7788就是一个灰度值。

感谢
